repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-added-large-files
      - id: debug-statements
        language_version: python3

  - repo: https://github.com/psf/black
    rev: 23.11.0
    hooks:
      - id: black
        args: [--safe]

  - repo: https://github.com/awslabs/git-secrets
    rev: 5357e18
    hooks:
      - id: git-secrets
        entry: git-secrets --scan
        files: .
        args: [--untracked]
